### ISSUE TITLE
Old meeting event post may be slightly misleading

### ISSUE THREAD

**Issue by TravisWhitehead** [osusec/osusec.github.io-archive#15]
In the lower-left corner of the main page an old event post for a meeting mentions Thursday meetings. This might be slightly misleading now that they're on Mondays. Also the timestamp appears to be in the future...

https://github.com/osusec/osusec.github.io/blob/master/events/_posts/2015-04-25-thursday-meeting.md

**Comment by captainGeech42** [comment]
Hmm, I'll take a look at that later this week. Thanks for bringing it up, I agree that could be confusing. Its on my to-do list to update the meetings listing with what we've had so far this term, but its a relatively low priority.

**Comment by khashf** [comment]
Fixed by PR https://github.com/osusec/osusec.github.io/pull/17
